apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
spec:
  nfs:
    server: h7.test.com
    path: /var/vols/test/demo1/prometheus-server
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager
spec:
  nfs:
    server: h7.test.com
    path: /var/vols/test/demo1/prometheus-alertmanager
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
